test

diff --git a/.github/workflows/certification-pipeline.yaml b/.github/workflows/certification-pipeline.yaml
--- a/.github/workflows/certification-pipeline.yaml
+++ b/.github/workflows/certification-pipeline.yaml
@@ -4,87 +4,87 @@ on:
   workflow_dispatch:
 
 jobs:
-  detect-changes:
-    name: Detect PR Changes
-    runs-on: ubuntu-latest
-    outputs:
-      modified_files: ${{ steps.changed-files.outputs.all_changed_files }}
-      plugin_name: ${{ steps.extract-plugin.outputs.plugin_name }}
-      package_yaml: ${{ steps.extract-plugin.outputs.package_yaml }}
-    steps:
-      # Checkout the repository
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-
-      # Identify modified plugin files
-      - name: Get Changed Files
-        id: changed-files
-        uses: tj-actions/changed-files@v41
-        with:
-          files: plugins/**/package.yaml
-
-      # Save repository as an artifact for later jobs
-      - name: Save Repository as Artifact
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: repo-artifact
-          path: |
-            plugins/
-            values.yaml
-            app-config-rhdh.yaml
-            rhdh/
-          retention-days: 7
-
-      - name: Confirm Artifact Upload
-        run: echo "Artifact repo-artifact uploaded successfully!"
-
-      # Extract plugin name and package.yaml path
-      - name: Extract Plugin Name and Package.yaml Path
-        id: extract-plugin
-        run: |
-          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
-          if [[ "$file" == plugins/*/package.yaml ]]; then
-            PLUGIN_NAME=$(echo "$file" | cut -d'/' -f2)
-            echo "PLUGIN_NAME=$PLUGIN_NAME" >> $GITHUB_OUTPUT
-            echo "PACKAGE_YAML=$file" >> $GITHUB_OUTPUT
-          fi
-          done
+#  detect-changes:
+#    name: Detect PR Changes
+#    runs-on: ubuntu-latest
+#    outputs:
+#      modified_files: ${{ steps.changed-files.outputs.all_changed_files }}
+#      plugin_name: ${{ steps.extract-plugin.outputs.plugin_name }}
+#      package_yaml: ${{ steps.extract-plugin.outputs.package_yaml }}
+#    steps:
+#      # Checkout the repository
+#      - name: Checkout Repository
+#        uses: actions/checkout@v4
+#
+#      # Identify modified plugin files
+#      - name: Get Changed Files
+#        id: changed-files
+#        uses: tj-actions/changed-files@v41
+#        with:
+#          files: plugins/**/package.yaml
+#
+#      # Save repository as an artifact for later jobs
+#      - name: Save Repository as Artifact
+#        if: always()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: repo-artifact
+#          path: |
+#            plugins/
+#            values.yaml
+#            app-config-rhdh.yaml
+#            rhdh/
+#          retention-days: 7
+#
+#      - name: Confirm Artifact Upload
+#        run: echo "Artifact repo-artifact uploaded successfully!"
+#
+#      # Extract plugin name and package.yaml path
+#      - name: Extract Plugin Name and Package.yaml Path
+#        id: extract-plugin
+#        run: |
+#          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
+#          if [[ "$file" == plugins/*/package.yaml ]]; then
+#            PLUGIN_NAME=$(echo "$file" | cut -d'/' -f2)
+#            echo "PLUGIN_NAME=$PLUGIN_NAME" >> $GITHUB_OUTPUT
+#            echo "PACKAGE_YAML=$file" >> $GITHUB_OUTPUT
+#          fi
+#          done
 
   setup-and-deploy:
     name: Setup and Deploy - ${{ needs.detect-changes.outputs.plugin_name }}
     runs-on: ubuntu-latest
-    needs: detect-changes
+#    needs: detect-changes
     steps:
       # Download repository artifact
-      - name: Download Repository Artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: repo-artifact
-          path: .
+#      - name: Download Repository Artifact
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: repo-artifact
+#          path: .
 
       # Verify that the artifact exists before proceeding
-      - name: 📝 Check if Artifact Exists
-        run: |
-          echo "🔍 Checking if 'repo-artifact' exists..."
-          ARTIFACT_NAME="repo-artifact"
-
-          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts")
-
-          echo "Response from GitHub API:"
-          echo "$RESPONSE" | jq
-
-          ARTIFACT_COUNT=$(echo "$RESPONSE" | jq "[.artifacts[]? | select(.name==\"$ARTIFACT_NAME\")] | length")
-
-          if [ "$ARTIFACT_COUNT" -eq 0 ]; then
-            echo "❌ ERROR: Artifact '$ARTIFACT_NAME' not found!"
-            exit 1
-          else
-            echo "✅ Artifact '$ARTIFACT_NAME' exists!"
-          fi
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#      - name: 📝 Check if Artifact Exists
+#        run: |
+#          echo "🔍 Checking if 'repo-artifact' exists..."
+#          ARTIFACT_NAME="repo-artifact"
+#
+#          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+#            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts")
+#
+#          echo "Response from GitHub API:"
+#          echo "$RESPONSE" | jq
+#
+#          ARTIFACT_COUNT=$(echo "$RESPONSE" | jq "[.artifacts[]? | select(.name==\"$ARTIFACT_NAME\")] | length")
+#
+#          if [ "$ARTIFACT_COUNT" -eq 0 ]; then
+#            echo "❌ ERROR: Artifact '$ARTIFACT_NAME' not found!"
+#            exit 1
+#          else
+#            echo "✅ Artifact '$ARTIFACT_NAME' exists!"
+#          fi
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       # Setup Kubeconfig before running Kubernetes commands
       - name: Set Up Kubeconfig
